application: freamonapp
version: 0
runtime: python
api_version: 1

handlers:
  - url: /css
    static_dir: css

  - url: /css/fonts
    static_dir: css/fonts

  - url: /js
    static_dir: js

  - url: /images
    static_dir: images

  - url: /.*
    script: typonotes.py
